export const APP_INIT = 'APP_INIT';
export const APP_INIT_START = 'APP_INIT_START';
export const APP_INIT_DONE = 'APP_INIT_DONE';
export const APP_STOP = 'APP_STOP';

export const APP_UPDATE_TIME = 'APP_UPDATE_TIME';
export const APP_DISMISS_ERROR = 'APP_HIDE_ERROR';

export const APP_SET_MODE = 'APP_SET_MODE';
export const APP_ADD_ROOM = 'APP_ADD_ROOM';
export const APP_SELECT_ROOM = 'APP_SELECT_ROOM';
export const APP_DESELECT_ROOM = 'APP_DESELECT_ROOM';

export const APP_SHOW_MODAL_CONFIRM = 'APP_SHOW_MODAL_CONFIRM';
export const APP_HIDE_MODAL_CONFIRM = 'APP_HIDE_MODAL_CONFIRM';

export const APP_ROOMS_REQUEST = 'APP_ROOMS_REQUEST';
export const APP_ROOMS_SUCCESS = 'APP_ROOMS_SUCCESS';
export const APP_ROOMS_FAILURE = 'APP_ROOMS_FAILURE';

export const ROOM_AGENDA_REFRESH = 'ROOM_AGENDA_REFRESH';
export const ROOM_AGENDA_REQUEST = 'ROOM_AGENDA_REQUEST';
export const ROOM_AGENDA_SUCCESS = 'ROOM_AGENDA_SUCCESS';
export const ROOM_AGENDA_FAILURE = 'ROOM_AGENDA_FAILURE';

export const ROOM_BOOKING_PANEL_OPEN = 'ROOM_BOOKING_PANEL_OPEN';
export const ROOM_BOOKING_PANEL_CLOSE = 'ROOM_BOOKING_PANEL_CLOSE';

export const ROOM_BOOKING_REQUEST = 'ROOM_BOOKING_REQUEST';
export const ROOM_BOOKING_SUCCESS = 'ROOM_BOOKING_SUCCESS';
export const ROOM_BOOKING_FAILURE = 'ROOM_BOOKING_FAILURE';

export const ROOM_REMOVE_BOOKING_REQUEST = 'ROOM_REMOVE_BOOKING_REQUEST';
export const ROOM_REMOVE_BOOKING_SUCCESS = 'ROOM_REMOVE_BOOKING_SUCCESS';
export const ROOM_REMOVE_BOOKING_FAILURE = 'ROOM_REMOVE_BOOKING_FAILURE';
